[tool.poetry]
name = "qmlcourse.ai"
version = "0.1.1"
description = ""
authors = ["SemyonSinchenko <semyonsinchenko@yahoo.com>"]
license = "CCBY-4.0"

[tool.poetry.dependencies]
python = ">=3.8,<=3.9"
PennyLane = "^0.18.0"
numpy = "^1.19.2"
matplotlib = "^3.3.4"
jupyter-book = "^0.10.1"
scikit-learn = "^0.24.1"
cirq = "^0.11.0"
pre-commit = "^2.13.0"
pyppeteer  = "^0.2.6"
pyyaml  = "^5.4.1"
qiskit = "^0.31.0"
dwave-system = "^1.10.0"
dwavebinarycsp = "^0.1.3"
networkx = "^2.6.3"
penaltymodel-maxgap = "^0.5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
