name: cd-prod

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  PUBLISH_BRANCH: web-page-master

jobs:

  create-folder-for-latex:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:

      - name: checkout to build branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.PUBLISH_BRANCH }}

      - run: |
          mkdir -p ./latex/

  build-and-deploy-book:
    needs: [create-folder-for-latex]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: github-pages
      url: https://quantum-ods.github.io/qmlcourse/

    steps:

      - name: checkout branch for build
        uses: actions/checkout@v3

      - name: install imagemagick
        run: |
          sudo apt install -y imagemagick

      - name: set up poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: set up py3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'poetry'

      - name: install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: build the book
        id: build_book
        env:
          DWAVE_TOKEN: ${{ secrets.DWAVE_TOKEN }}
        run: |
          poetry run jupyter-book toc migrate /home/runner/work/qmlcourse/qmlcourse/qmlcourse/_toc.yml -o /home/runner/work/qmlcourse/qmlcourse/qmlcourse/_toc.yml
          poetry run jupyter-book build ./qmlcourse

      - name: update publish dir to build branch
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qmlcourse/_build/html/
          publish_branch: ${{ env.PUBLISH_BRANCH }}

      - name: build latex files
        env:
          DWAVE_TOKEN: ${{ secrets.DWAVE_TOKEN }}
        run: |
          sudo apt-get install texlive-latex-extra texlive-fonts-extra texlive-xetex latexmk
          poetry run jupyter-book build ./qmlcourse --builder latex

      - name: create pdf book
        continue-on-error: true
        run: |
          cd ./qmlcourse/_build/latex/
          xelatex -interaction=nonstopmode qmlcourse.tex

      - name: send pdf book to build branch
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qmlcourse/_build/latex/
          destination_dir: ./latex/
          publish_branch: ${{ env.PUBLISH_BRANCH }}
