# Test docker for dev and listner
name: test-docker

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:

  deploy_book:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: checkout branch for build
        uses: actions/checkout@v2
      - name: set up docker
        uses: actions/setup-docker@v1
      - name: test dev (qml-dev) docker
        run: |
          docker build . --tag qml-dev:latest --target dev
      - name: test listener (qmlcourse) docker
        run: |
          docker build . --tag qmlcourse:latest --target listener